name: kale
grade: stable
version: v0.8.0
base: core18

icon: icon.png

summary: Highlight Logs

description: >
  Kale is a command-line tool that highlights logs.

confinement: strict

apps:
  kale:
    command: bin/kale
    plugs:
      - home

parts:
  kale:
    source: .
    plugin: nodejs
    nodejs-version: 14.3.0
    nodejs-package-manager: yarn
    build-packages: ['libcurl4-openssl-dev', 'git']
