name: kale
grade: stable
version: v0.6.0
base: core18

icon: icon.svg

summary: highlight logs.

description: >
  Kale (colour-tail -> cail -> kale) behaves similarily to tail's live-follow mode, but with
  extra support for highlighting streamed text.

confinement: strict

apps:
  kale:
    command: bin/kale

parts:
  kale:
    source: .
    plugin: nodejs
    nodejs-version: 14.3.0
    nodejs-package-manager: yarn
    build-packages: ['libcurl4-openssl-dev', 'git']
