name:        kale
version:     v0.3.0
summary:     highlight streamed text.
description: >
  Kale (colour-tail -> cail -> kale) behaves similarily to tail's live-follow mode, but with
  extra support for highlighting streamed text.

apps:
  kale:
    command: bin/kale

parts:
  kale:
    plugin: nodejs
    node-packages:
      - rgrannell1/kale
    node-engine: 7.10.0

confinement: strict
grade:       devel
